### ISSUE TITLE
论文分享

### ISSUE THREAD

**Issue by ZhaoqiangShen** [denkywu/SAR-Synthetic-Aperture-Radar#1]
您好，我最近在学习合成孔径雷达。能否把您的硕士论文题目发给我一下，或者您发表的其它论文？

**Comment by denkywu** [comment]
你好。不好意思刚看到消息。我的硕士论文你在知网上应该查不到，所以就不提供了哈哈。
SAR、insar 方面的几本基础书，极化sar方面的几篇论文，可以参考下这个帖子里写的 https://blog.csdn.net/denkywu/article/details/106949725?spm=1001.2014.3001.5501
