### ISSUE TITLE
关于SAR成像数据处理中的一个小问题

### ISSUE THREAD

**Issue by JinZhi-Escape** [denkywu/SAR-Synthetic-Aperture-Radar#4]
在您的SAR处理代码中，我关注到不管是cs还是rd算法，您都把数据矩阵在变换到rd域之前都进行了数据搬移（`s_rd = s_echo.*exp(-1j*2*pi*fnc.*(ta.'*ones(1,Nrg))); 	% 数据搬移`），请问为什么会多出来这一步？
我的理解不管是RDA还是CS，在变换到rd域之前方位向的信息应该是没有受到影响，但是当我尝试把它删掉后图像确实出现问题了。

**Comment by denkywu** [comment]
数据搬移这个词可能用的不准确，但是是比较关键的一步。当年为了理解它（其实就是方位向频率轴的问题）花了很长时间，也是卡在这里很久，确实，只要没有这步就会有问题。所以我印象深刻。
现在试着回答下（因为我可能没法准确说出了）：思考的方向就是变换到距离多普勒域后方位向频率轴如何对齐，如何进行方位压缩的事。我刚看了下代码，在这步之后有一个设置方位向频率轴的，如下

% 设置方位频率轴——关键点！！！
fa = fnc + fftshift(-NFFT_a/2:NFFT_a/2-1)/NFFT_a*Fa;    % 方位频率轴如此设置。

上面的“数据搬移”是为了让数据在“% 方位向傅里叶变换，到距离多普勒域”后，与上面的方位频率轴是对应的。由此才有后面代码中 方位压缩中  方位向频率轴是对齐的

% --------------------------------------------------------------------
% 方位压缩
% --------------------------------------------------------------------
fa_azimuth_MF = fa;         % 方位频率轴，采用和RCMC中所用的频率轴相同。
Ka = 2*Vr^2*(cos(sita_r_c))^3./(lamda.* R0_RCMC);  	% 方位向调频率，是随最近斜距R0变化的。
Ka_1 = 1./Ka;                                       % 为了方便计算，先取倒数。
Haz = exp( -1j*pi.*(((fa_azimuth_MF).').^2*Ka_1) );	% 方位向匹配滤波器
% 这里要注意，生成的MF的零频既不是在两端，也不是在中心的。
% 考虑下频率轴是什么样的，间断点在哪里。注意fa的构成。
% 这里的频率轴和距离多普勒域的方位频谱是对应的。

S_rd_c = S_rd_rcmc.*Haz;            % 乘以匹配滤波器

楼主可以仔细观察下这几个变量 fa_azimuth_MF ，fa，S_rd_rcmc 他们的方位向肯定是对齐的。

之所以说“频率搬移”可能不准确，但是也算准确，就死因为这个词是实践过程中来表明这一步的，我倒确实没在文献里面看到这种说法，毕竟这种代码实践的细节不属于文献所述内容。
另外，楼主也可以删去代码不进行这样的“频率搬移”，但是，但是，但是（重要的话说三遍），那方位向频率轴的设置就不能是我源代码中那样，楼主需要自行修改。只要将方位向的频率轴改的，和不进行频率搬移的数据  也是对齐的，那结果也一定是ok的。

以上。
（辩证的看我上面的话哈，毕竟已经很多年了，别给你带新的沟里）

**Comment by JinZhi-Escape** [comment]
okok，我自己再看看书和代码。感谢您的回复，哈哈。
